---
- name: Set hostname
  hostname:
    name: "{{ pxe_server_hostname }}"
  tags: [system, hostname]

- name: Configure timezone
  timezone:
    name: "{{ pxe_server_timezone }}"
  tags: [system, timezone]

- name: Install essential packages
  dnf:
    name:
      - epel-release
      - wget
      - curl
      - vim
      - htop
      - net-tools
      - bind-utils
      - tcpdump
      - iotop
      - sysstat
      - lsof
      - strace
      - gcc
      - make
      - python3-pip
      - python3-devel
      - openssl
      - ca-certificates
      - ntp
      - chrony
    state: present
  tags: [system, packages]

- name: Configure NTP/Chrony
  template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart chronyd
  tags: [system, ntp]

- name: Configure system limits
  template:
    src: limits.conf.j2
    dest: /etc/security/limits.conf
    owner: root
    group: root
    mode: '0644'
  tags: [system, limits]

- name: Configure sysctl parameters
  template:
    src: sysctl.conf.j2
    dest: /etc/sysctl.conf
    owner: root
    group: root
    mode: '0644'
  notify: reload sysctl
  tags: [system, sysctl]

- name: Create system users
  user:
    name: "{{ item.name }}"
    uid: "{{ item.uid }}"
    group: "{{ item.group }}"
    shell: "{{ item.shell | default('/bin/bash') }}"
    home: "{{ item.home | default('/home/' + item.name) }}"
    create_home: "{{ item.create_home | default(true) }}"
    system: "{{ item.system | default(false) }}"
  loop:
    - name: foreman
      uid: 1000
      group: foreman
      system: true
      home: /opt/foreman
    - name: pxe
      uid: 1001
      group: pxe
      system: true
      home: /opt/pxe
  tags: [system, users]

- name: Create system groups
  group:
    name: "{{ item }}"
    system: yes
  loop:
    - foreman
    - pxe
    - tftp
  tags: [system, groups]

- name: Configure firewall
  firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
  loop:
    - ssh
    - http
    - https
    - dns
    - tftp
    - dhcp
  notify: reload firewalld
  tags: [system, firewall]

- name: Configure SELinux
  seboolean:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    persistent: yes
  loop:
    - name: httpd_can_network_connect
      state: yes
    - name: httpd_can_network_relay
      state: yes
    - name: tftp_home_dir
      state: yes
  tags: [system, selinux]

- name: Create required directories
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0755') }}"
  loop:
    - path: /var/lib/tftpboot
      owner: tftp
      group: tftp
      mode: '0755'
    - path: /var/lib/foreman-reports
      owner: foreman
      group: foreman
      mode: '0755'
    - path: /opt/pxe
      owner: pxe
      group: pxe
      mode: '0755'
    - path: /var/log/pxe
      owner: pxe
      group: pxe
      mode: '0755'
  tags: [system, directories]
